#Makefile
# 適当に書いたので省略形カクべし
#all: Maxwell1d Maxwell2d
all: Maxwell2d
# invoke undefined behaviorがでるので時間があるときにまた
#Maxwell1d: MaxwellCIP1d.c
#	gcc -O2 MaxwellCIP1d.c -lm -o maxwell1d
Maxwell2d: MaxwellCIP2d.c
	gcc -O2 MaxwellCIP2d.c -lm -o maxwell2d
